language: python

dist: xenial

arch:
    - amd64
    - arm64

cache: 
    - pip
    - steamconfig.py

python:
    - "3.4"
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8"
    - "nightly"

matrix:
    allow_failures:
        - python: "nightly"

install:
    - pip3 install --upgrade pip
    - pip3 install -r requirements.txt
    - pip3 install pytest

script:
    - pytest steam.py