language: python

os:
    - linux

dist: xenial

arch:
    - amd64
    - arm64

cache: 
    - pip
    - steamconfig.py

python:
    - "3.7"
    - "3.8"
    - "nightly"

jobs:
    allow_failures:
        - python: "nightly"

install:
    - python3 -m pip install --upgrade pip
    - pip3 install -r requirements.txt
    - pip3 install pytest

script:
    - pytest steam.py
    - sonar-scanner

addons:
  sonarcloud:
    organization: "nickwasused"
    token:
      secure: ${GCE_SECRET_KEY}