language: python

jobs:
  include:
    - name: "Linux"
        os:
            - linux

        dist: xenial

        arch:
            - amd64
            - ppc64le
            - s390x
            - arm64

        cache: 
            - pip
            - steamconfig.py

        python:
            - "3.6"
            - "3.7"
            - "3.8"
            - "nightly"

    - name: "Windows"
        os: windows
        language: shell
        before_install:
          - choco install python --version 3.8.0
          - python -m pip install --upgrade pip
        env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

        jobs:
            allow_failures:
                - python:
                      "nightly"

install:
- python3 -m pip install --upgrade pip
- pip3 install -r requirements.txt
- pip3 install pytest
- pip3 install codecov
            
script:
- pytest steam.py
- coverage run steam.py
    
after_success:
  - codecov
