on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


name: Create Release

jobs:
  pyinstaller:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'windows-latest']

      fail-fast: true
      max-parallel: 1

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Dependencies
      run: pip3 install --upgrade
        pyinstaller
        requests
        setuptools
        wheel

    - name: Build
      working-directory: app
      run: pyinstaller
        FreeGamesonSteam.spec

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}
        path: app/dist/*
