on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]


name: Create Release

jobs:
  pyinstaller:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ['ubuntu-20.04', 'windows-latest']

      fail-fast: true
      max-parallel: 1

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Dependencies
      run: pip3 install --upgrade
        pyinstaller
        requests
        setuptools
        wheel

    - name: Strip
      id: strip
      run: echo ::set-output name=option::--strip
      if: runner.os != 'Windows'

    - name: Build
      working-directory: app
      run: pyinstaller
        ${{ steps.strip.outputs.option }}
        FreeGamesonSteam.spec

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ runner.os }}-package
        path: app/dist/*
        
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@release-1.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          releaseId: ${{ needs.create_release.outputs.id }}
          args: '/app/dist/*'

        

